from zone import Door, DoorKey, Position
from astar import Node
from utils import waitFrames
from bag import BIKE_ID

import heapq

import img
import game
import zone
import astar
import action
import player
import joypad
import memory
import pokemon

DOOR_GRAPH = {}

##########################################################################################################
#                                                                                                        #
#     Methods responsible of exploiting paths generated by A* algorithm and generating input presses     #
#                                                                                                        #
##########################################################################################################

#######################################################################
# Proxy method to add gameData parameters before calling astar method #
#######################################################################
def getMostEfficientPath(start: Position, end: Position, zoneMap = None, isBelow = None, maxCost = None):
    return astar.getMostEfficientPath(start, end, game.getGameData().repelSteps > 0, zoneMap, isBelow, maxCost)



######################################################################################################
# Generate every input needed to go through the provided node list and check if the path is followed #
######################################################################################################
def processPath(nodeList):
    print(nodeList)

    # Send all inputs needed to go to specified location to emulator
    joypad.writePathfindingInput(nodeList)
    
    # Make sure the path is followed, correct it if needed
    checkPathIsFollowed(nodeList)



##############################################################################
# Make sure the player is following the provided path, and correct if needed #
##############################################################################
def checkPathIsFollowed(path):

    # We might bump into walls or moving NPCs, ecounter wild Pokémon, etc
    # So we need to make sure the player follows the right path
    #
    # Only stop path processing when all inputs have been pressed and the player is at desired location

    gameData = game.getGameData()
    playerPosition = player.getPlayerData().position

    isRepelActive = (gameData.repelSteps > 0)
    pathIndex = 0

    while memory.readJoypadData() or playerPosition != path[-1].position:

        # Don't check memory more than once a frame to avoid overloading the CPU
        waitFrames(1)

        # Get current game and player data
        gameData = game.getGameData()
        playerPosition = player.getPlayerData().position

        # Non-0 PID : we're in a battle - stop pathfinding and let main script take over
        if (memory.readWildPokemonData().get("pid",0) != 0):
            print("Encountered wild Pokémon")
            memory.clearJoypadInputs() # Clear input
            break

        # Repel no longer active, stop moving and use another one
        elif (isRepelActive and gameData.repelSteps == 0):
            memory.clearJoypadInputs() # Clear input
            joypad.writeInputAndWait("@@@@A") # Wait for the dialogue to be displayed and skip it
            action.useItem(repel = True) # Use Repel and go back to overworld

        # Reached the end or went to another zone, clear all inputs and go back to main loop
        elif (playerPosition == path[-1].position or playerPosition.zone.zoneId != path[-1].position.zone.zoneId):
            memory.clearJoypadInputs() # Clear input
            break

        # Check character progression through the path
        elif (path[pathIndex].position != playerPosition):

            # Normal behavior : character went to next position
            if (path[pathIndex + 1].position == playerPosition):
                pathIndex += 1

            # Specific case : we don't keep track of Rock Climb positions, false positive
            elif (playerPosition.zone.map[playerPosition.Y][playerPosition.X] == "C"):
                continue

            # Specific case : Waterfall position is skipped, false positive
            elif (path[pathIndex + 1].cellType == "w"):
                pathIndex += 1
                continue

            # We could be at a different position because we're in a different zone, go back to main loop
            elif (path[pathIndex].position.zone != playerPosition.zone):
                break

            # Wrong path : recalculate from current position
            else:
                memory.clearJoypadInputs() # Clear input

                # Make sure player is not moving anymore before starting moving again
                waitFrames(15) # Wait 15 frames (time needed to completely stop)

                # Calculate path from new position to the rest of the correct path
                path = writePathInputsFromCurrentState(path, pathIndex + 1)
                pathIndex = 0

        # No more inputs left to process
        elif (not memory.readJoypadData()):

            # Make sure player is not moving anymore before checking his position
            waitFrames(15) # Wait 15 frames (time needed to completely stop)
            playerPosition = player.getPlayerData().position

            # Poketch not visible, we changed zone, go back to main loop
            if (not img.poketch.isOnScreen()):
                break
            # Reached the end, go back to main loop
            elif (playerPosition == path[-1].position):
                break
            # Not at the desired location, calculate path from this position to the rest of the correct path
            else:
                path = writePathInputsFromCurrentState(path, pathIndex + 1)
                pathIndex = 0

        # Entered a foggy area : use Defog
        elif (gameData.isFoggy):
            memory.clearJoypadInputs() # Clear input
            action.useHM(pokemon.DEFOG_ID) # Use Repel and go back to overworld



##############################################################################################
# Erase inputs and start again from the already processed nodes and the current player state #
##############################################################################################
def writePathInputsFromCurrentState(nodeList, breakNodeId):

    # Get final position after player stopped moving
    playerData = player.getPlayerData()

    # If on a bike slope, just wait, we'll slide down eventually
    while (playerData.position.getCell() == "V"):
        waitFrames(1)
        playerData = player.getPlayerData()

    # a/A cells are either above or below a bridge, check the first remaining node to differentiate
    if (playerData.position.getCell() in ["a","A"]):
        isBelow = nodeList[breakNodeId].isBelow
    else:
        isBelow = None

    print("Wrong path ! Start again from " + str(playerData.position))

    # If we need a new path while on a bike slope, start the go-up-the-slope sequence again
    while (breakNodeId >= 0 and nodeList[breakNodeId].onABikeSlope):
        breakNodeId -= 1

    # Split the original nodeList into processed and remaining nodes
    processedNodes = nodeList[:breakNodeId]
    remainingNodes = nodeList[breakNodeId:]

    # Update the map to take into account the pushed boulder and destroyed obstacles
    updatedMap, strengthUsed, destroyedObstacles = astar.getMapAtCurrentState(processedNodes, nodeList[0].position.zone.map)

    # Go from player position to first node of the remaining nodes
    firstNode = remainingNodes.pop(0)
    nodeList = getMostEfficientPath(playerData.position, firstNode.position, updatedMap, isBelow)
    nodeList.extend(remainingNodes)

    # Retrieve all inputs needed to go to specified location
    joypad.writePathfindingInput(nodeList, strengthUsed, destroyedObstacles)

    return nodeList






#########################################################################################################
#                                                                                                       #
#     Methods responsible of using Dijsktra's algorithm to find door-to-door paths across the world     #
#                                                                                                       #
#########################################################################################################

###########################################
# DoorNode class for Dijkstra Pathfinding #
###########################################
class DoorNode():
    def __init__(self, fromDoor: Door, toDoor: Door, path = None):
        self.fromDoor = fromDoor
        self.toDoor = toDoor
        self.path = path

        if (path):
            self.weight = self.path[-1].g
        else:
            self.weight = fromDoor.position.getDistanceTo(toDoor.position)

    def __eq__(self, other):
        if isinstance(other, DoorNode):
            return self.fromDoor == other.fromDoor and self.toDoor == other.toDoor
        return False
    
    def __str__(self):
        return "Weight " + str(self.weight) + " from (" + str(self.fromDoor) + ")\n           to (" + str(self.toDoor) + ")\n"
    
    def __repr__(self):
        return str(self)


########################################################################
# Populate DOOR_GRAPH by adding every neighbour to every possible door #
# Takes around 50 minutes to generate, so we store it in a pkl file    #
########################################################################
def initDoorGraph():

    # Iterate on every single Door
    for zoneObject in zone.ZONELIST:
        for door in zoneObject.doorList:

            # Only process doors connected to another door
            if (not door.connectedDoor):
                continue

            # Create tuple object used as key from the door and its connected door
            doorKey = door.createDoorKey()

            for otherDoorInZone in zoneObject.doorList:

                # Only process the other doors connected to another zone
                if (not otherDoorInZone.connectedDoor or door == otherDoorInZone):
                    continue

                # Calculate A* path from each door to its neigbours 
                doorPath = getMostEfficientPath(door.connectedDoor.destination, otherDoorInZone.position)

                # Only add the door path if there's an actual path
                if (doorPath):
                    DOOR_GRAPH.setdefault(doorKey, []).append(DoorNode(door, otherDoorInZone, doorPath))

    # Save graph as a file to easily retrieve it at a later execution
    memory.saveGraph(DOOR_GRAPH, 'data/pkl/graph.pkl')



########################################################################################
# Calculate the total cost of the path from player position to provided world location #
########################################################################################
def calculateWorldPathCost(location):
    pathCost = 0

    # Retrieve node-to-node complete path needed to reach location
    flyCity, completePath = generateWorldPath(location)
    completeNodePath = processWorldPath(completePath, location.destination if isinstance(location, Door) else None, calculateScore = True)

    # Add each node list total cost to get the whole path cost
    for nodeList in completeNodePath:
        pathCost += nodeList[-1].g

    return pathCost



###################################################################################
# Retrieve the best possible path from any door to another and process the inputs #
###################################################################################
def goToWorldLocation(location):

    # Keep searching until we're at the desired postion
    correctPath = False

    while (not correctPath):
        needToDig = False
        playerPosition = player.getPlayerData().position
        flyCity, completePath = generateWorldPath(location)

        # Location is too far from current player position, so we fly to a close city before
        if (flyCity):

            # If we need to fly, we also need to be in a zone that enables it, or at least dig our way out
            if (not playerPosition.zone.canFly):

                # Get out of the zone before using Dig or Fly
                if (not playerPosition.zone.canDig):
                    endPosition, pathToExit = findClosestFlyDigZone(playerPosition)
                    correctPath = processWorldPath(pathToExit, endPosition)

                    # Failed to find the correct path : start the process again
                    if (not correctPath):
                        continue

                    needToDig = not endPosition.zone.canFly

                # We can Dig our way out to go to a zone enabling Fly
                else:
                    needToDig = True

                # Still can't Fly but can Dig : use HM
                if (needToDig):
                    action.useHM(pokemon.DIG_ID)

            # Use Fly to go to the closest city
            action.useHM(pokemon.FLY_ID, flyCity)

        # Process generated path
        correctPath = processWorldPath(completePath, location.destination if isinstance(location, Door) else None)



################################################################################
# Convert all paths to Node paths and follow them until we reached destination #
################################################################################
def processWorldPath(worldPath, endPosition, calculateScore = False):
    completeNodePath = []
    lastDoors = []

    # Each subpath can be either a door-to-door or a node-no-node path
    for subPath in worldPath:

        if (subPath):
            pathList = []
            firstElement = subPath[0]
            
            # Node-to-node path
            if (isinstance(firstElement, Node)):
                pathList = [subPath]

            # Door-to-door path
            elif (isinstance(firstElement, DoorKey)):
                pathList = getPathFromGraph(subPath)

            # Add each door in a list to later retrieve transition time between zones
            for path in pathList:
                lastPosition = path[-1].position
                lastDoors.append(lastPosition.zone.getDoorByPosition(lastPosition))

            completeNodePath += pathList

    # If we just want to calculate path score, we can return the path without processing it
    if (calculateScore):
        return completeNodePath
 
    # Process every subpath between each doors
    for pathId in range(len(completeNodePath)):

        # Process current path
        currentPath = completeNodePath[pathId]

        # Make sure bike is the registered key item if needed since we'll be pressing Y to use it
        if (game.getGameData().registeredKeyItem != BIKE_ID):
            for node in currentPath:
                if (node.canBike()):
                    action.useItem(BIKE_ID, register = True, use = False)
                    break

        # Close menu if open
        if (img.getMenuPosition()):
            joypad.writeInputAndWait("B")

        # Go from starting node to ending node
        processPath(currentPath)

        # Only continue when all inputs have been processed
        while (memory.readJoypadData()):
            waitFrames(1)

        # Only apply door animation between paths, or if the final position is a door destination
        if (pathId + 1 < len(completeNodePath) or endPosition):

            # Wait until we reach the first position of the next zone
            framesOnOverworld = 0
            nextPosition = completeNodePath[pathId + 1][0].position if pathId + 1 < len(completeNodePath) else endPosition

            while (player.getPlayerData().position != nextPosition and framesOnOverworld < 300):
                waitFrames(1)

                # Count the number of frames while poketch is visible
                if (img.poketch.isOnScreen()):
                    framesOnOverworld += 1

                # Spent 2 seconds on the wrong position while on the overworld : start again
                if (framesOnOverworld > 120):
                    return False

            # Wait poketch is visible (after transition screen)
            while (not img.poketch.isOnScreen()):
                waitFrames(1)

            # Moving from door to actual end position, wait for walking animation to be over
            print("Wait " + str(lastDoors[pathId].transitionTime) + " frames")
            waitFrames(lastDoors[pathId].transitionTime)

    # Reached the final position
    return True


####################################################################
# Generate all nodes lists needed to go from one door to any other #
####################################################################
def getPathFromGraph(doorToDoorPath):
    
    # Cannot find path if there's only one door
    if (len(doorToDoorPath) > 1):
        
        # We're using currentDoorKey and nextDoorKey to navigate from path to path, starting from start door
        completePath = []
        currentDoorKey = doorToDoorPath.pop(0)
        nextDoorKey = doorToDoorPath.pop(0)

        while True:
            # Get all paths from the current door
            possiblePaths = DOOR_GRAPH[currentDoorKey]

            for doorNode in possiblePaths:

                # Search all possible paths until we found a door leading to the next door in the global path
                if (doorNode.fromDoor in currentDoorKey and doorNode.toDoor in nextDoorKey):

                    # Add subpath to global path and continue the process with the next door
                    completePath.append(doorNode.path)
                    currentDoorKey = doorNode.toDoor.connectedDoor.createDoorKey()

                    # Keep searching if there are doors left in the path
                    if (len(doorToDoorPath) > 0):
                        nextDoorKey = doorToDoorPath.pop(0)
                    else:
                        return completePath
                    
                    # We found a path from current door to next door, we can skip the rest of the possible paths
                    break

                # Not supposed to reach this point, print debug logs for now
                elif (doorNode == possiblePaths[-1]):
                    print("\nDidn't find a path from " + str(currentDoorKey) + " to " + str(nextDoorKey))
                    print(*possiblePaths, sep = "\n", end = "\n")
                    return None


#######################################################
# Find best path from a door to another in DOOR_GRAPH #
#######################################################
def getShortestDoorPath(start: Door, end: Door):
    print("Find shortest path from " + str(start) + " to " + str(end))

    # Create keys from doors in order to read in the DOOR_GRAPH
    keyStart = start.createDoorKey()
    
    # Use Dijkstra to retrieve every possible path from starting door
    paths = dijkstra(keyStart)[0]

    # Make the path readable and return it
    return processDijkstraPath(paths, end)


#######################################################################################
# Take paths generated by Dijsktra's and find the one leading to the destination door #
#######################################################################################
def processDijkstraPath(paths, destination):

    # Create key from destination door in order to read in the DOOR_GRAPH
    if isinstance(destination, Door):
        keyEnd = destination.createDoorKey()
    else:
        keyEnd = destination

    # Retrieve the path from end door to starting door
    subPath = paths.get(keyEnd, None)

     # Return None if no path has been found
    if (not subPath):
        return None
    
    # Init fullPath to end position
    fullPath = [keyEnd]
    
    # Go from door to door
    while subPath is not None:
        fullPath.append(subPath)
        subPath = paths.get(subPath, None)

    # Reverse the full path to get path from start to end
    return fullPath[::-1]


########################################################################
# Use Dijsktra's algorithm to find all paths and distances from a door #
########################################################################
def dijkstra(startingDoor):

    # Map the path/distance from each possible door to the starting door
    path = {}
    visited = {startingDoor: 0}

    # Retrieve every possible door from the doorGraph, we'll remove them once processed
    doors = set(DOOR_GRAPH.keys())
    queue = [(0, startingDoor)]
    
    # We keep searching while there are doors to process
    while doors and queue:

        # Take the closest door in the queue
        current_distance, current_door = heapq.heappop(queue)

        # Door has already been processed or does not exist, take another door
        if current_door not in doors:
            continue

        # We're processing the door, remove them from the set
        doors.remove(current_door)

        # Take every neighbour door
        for door_node in DOOR_GRAPH[current_door]:

            # Retrievei its destination and ts distance to the current door
            neighbor = door_node.toDoor.createDoorKey()
            distance = current_distance + door_node.weight

            # We keep the neighbor if it hasn't ben processed or if the current path is shorter
            if neighbor not in visited or distance < visited[neighbor]:
                
                # We'll check for its neighbors in another iteration
                heapq.heappush(queue, (distance, neighbor))

                # Update the path and distance from starting door
                path[neighbor] = current_door
                visited[neighbor] = distance

    # Once there's no more door to process, return the whole map
    return path, visited


################################################################################################
# Path class used by generateWorldPath method to store path data from city or current position #
################################################################################################
class Path():
    def __init__(self):
        self.lastDoorDestination = None # First position the player will be after going through the last door
        self.dijsktraPath = None        # Complete path the player needs to follow from position to last door
        self.dijsktraDistance = 0       # Distance from position to last door
        self.finalPath = None           # Complete path the player needs to follow from last door to reach destination
        self.finalDistance = 0          # Distance from last door to destination


#######################################################################################################
# Choose between flying to a position or directly go to it, and return the complete node-to-node path #
#######################################################################################################
def generateWorldPath(location, skipAllCityProcesses = False):
    
    # Need to go to a Position but only Door paths are pretermined, find closest Door
    if isinstance(location, Position):
        closestDoor = getClosestDoor(location)
        destination = location

    # Need to go to a Door, just use predetermined paths
    elif isinstance(location, Door):
        closestDoor = location
        destination = location.position

    minDistanceFromCity = 9999
    closestCity = None
    locationDoorKey = closestDoor.createDoorKey()

    # Check every possible city and keep the closest
    for city in zone.CITY_LIST:
        cityDoorKey = city.flyDoor.createDoorKey()

        # Get all possible paths from city
        paths, distances = dijkstra(cityDoorKey)

        # Only search for cities that can actually reach location
        if (locationDoorKey in distances):
            distanceFromLocation = distances[locationDoorKey]

            # Save closest city when distance to location is the lowest
            if (distanceFromLocation < minDistanceFromCity):
                minDistanceFromCity = distanceFromLocation
                distancesFromCity = distances
                pathsFromCity = paths
                closestCity = city

    # We found location's closest city, but there might be a better path from our current position
    playerPosition = player.getPlayerData().position
    playerPath = Path()
    cityPath = Path()
    
    # Generate complete dijsktra path from city to closest door
    cityPath.dijsktraPath = processDijkstraPath(pathsFromCity, locationDoorKey)
    cityPath.dijsktraDistance = minDistanceFromCity
    skipAllCurrentPositionProcesses = False
    
    # Check if we can reach the location from our current position
    directPathFromCurrentPosition = getMostEfficientPath(playerPosition, destination)

    # Direct path between player and destination
    if (directPathFromCurrentPosition):
        playerPath.finalDistance = directPathFromCurrentPosition[-1].g
        playerPath.dijsktraPath = [directPathFromCurrentPosition]

    # No direct path available from player position, find the nearest door to current position to estimate the distance
    else:
        closestPositionDoor, pathToDoor = getBestPathDoor(playerPosition, closestDoor.createDoorKey())

        # There might be no door from our current position that leads to destination (probably on another island)
        if (not closestPositionDoor):
            print("Can't reach destination from current position, we have to fly")
            skipAllCurrentPositionProcesses = True
    
        # Populate playerPath object by calculating final door, distance to door and distance from door
        if (not skipAllCurrentPositionProcesses):
            getPlayerDistance(playerPath, destination, closestDoor, closestPositionDoor, pathToDoor)

    # Don't fly if the destination or the city is close to our current position
    if (not skipAllCurrentPositionProcesses):

        # If the destination is within 100 cells, directly go to it
        if (playerPath.dijsktraDistance + playerPath.finalDistance < 50):
            print("If the destination is within 50 cells, directly go to it")
            skipAllCityProcesses = True

        # If the city is within 50 cells, don't fly to it
        elif (getMostEfficientPath(playerPosition, closestCity.flyDoor.position, maxCost = 50)):
            print("Don't fly to the closest city if it is within 50 cells")
            skipAllCityProcesses = True


    # Populate cityPath object by calculating final door, distance to door and distance from door
    if (not skipAllCityProcesses and isinstance(location, Position)):
        getCityDistance(cityPath, destination, closestDoor, closestCity, distancesFromCity)
    else:
        cityPath.dijsktraPath = [cityPath.dijsktraPath]

    # Just fly to city if the distance is 0
    if (not skipAllCityProcesses and cityPath.dijsktraDistance + cityPath.finalDistance == 0):
        print("Just fly to city if the distance is 0")
        skipAllCurrentPositionProcesses = True


    # We'll use a distance ratio, fly if the player is too far and bike otherwise
    if (not skipAllCityProcesses and not skipAllCurrentPositionProcesses):
        distanceRatio = (playerPath.dijsktraDistance + playerPath.finalDistance) / (cityPath.dijsktraDistance + cityPath.finalDistance)
        print("(" + str(playerPath.dijsktraDistance) + " + " + str(playerPath.finalDistance) + ") / (" + str(cityPath.dijsktraDistance) + " + " + str(cityPath.finalDistance) + ") = " + str(distanceRatio))

    # Ratio is in favor of flying
    if (not skipAllCityProcesses and (skipAllCurrentPositionProcesses or distanceRatio > 1.2)):
        return closestCity, cityPath.dijsktraPath + ([cityPath.finalPath] if isinstance(location, Position) else [])

    # Ratio is neutral or in favor of direct path, and if neutral we choose the direct path
    else:
        return None, playerPath.dijsktraPath + ([playerPath.finalPath] if isinstance(location, Position) else [])


#############################################################################################################
# Returns last door you need to go through, its distance from the city, and its distance to the destination #
#############################################################################################################
def getCityDistance(cityPath, destination, closestDoor, closestCity, distancesFromCity):

    # Closest door is Pokemon Center door, there's only a direct path to calculate
    if (closestDoor in [closestCity.flyDoor, closestCity.flyDoor.connectedDoor]):
        cityPath.lastDoorDestination = closestDoor.connectedDoor.destination
        cityPath.finalPath = getMostEfficientPath(cityPath.lastDoorDestination, destination)
        cityPath.finalDistance = cityPath.finalPath[-1].g

        # Direct path from outside door : skip dijsktraPath
        if (closestDoor == closestCity.flyDoor):
            cityPath.dijsktraPath = []
            cityPath.dijsktraDistance = 0
        
        # Direct path from inside door : just go through the door
        else:
            cityPath.dijsktraPath = [getMostEfficientPath(closestCity.flyDoor.connectedDoor.destination, closestCity.flyDoor.position)] # Just go up
            cityPath.dijsktraDistance = cityPath.dijsktraPath[0][-1].g # Normally just 1

    # Need to go through at least one door
    else:
        nextDoor = cityPath.dijsktraPath[1][0]
        insideZone = closestCity.flyDoor.destination.zone
        insideDoor = False

        # Check if we're starting from outside or inside door
        if (insideZone in [nextDoor.destination.zone, nextDoor.position.zone]):
            lastSubpathDoor = closestCity.flyDoor
            insideDoor = True
        else:
            lastSubpathDoor = closestCity.flyDoor.connectedDoor

        # Check if any of the doors before closestDoor can reach the destination
        for doorId in range(0, len(cityPath.dijsktraPath)):

            # Check if we can directly reach destination from there
            cityPath.finalPath = getMostEfficientPath(lastSubpathDoor.destination, destination)

            if (cityPath.finalPath):
                break

            # We couldn't find a path from last door, keep following the path
            lastSubpathDoor = getLastDoorInPath(cityPath.dijsktraPath[doorId], cityPath.dijsktraPath[doorId + 1])

        # Update dijsktraPath with the new last door destination
        cityPath.lastDoorDestination = lastSubpathDoor.destination
        cityPath.dijsktraPath = [cityPath.dijsktraPath[:doorId + 1]]
        cityPath.finalDistance = cityPath.finalPath[-1].g 

        # Direct path between city and closestDoor
        if (len(cityPath.dijsktraPath[0]) == 1):
            cityPath.dijsktraPath = [] # Skip dijsktraPath
            cityPath.dijsktraDistance = 0

        # Need to go through doors
        else:
            cityPath.dijsktraDistance = distancesFromCity[cityPath.dijsktraPath[0][-1]]

        # If we're starting from inside, we just need to add the path to actually enter the door
        if (insideDoor):
            cityPath.dijsktraPath = [getMostEfficientPath(closestCity.flyDoor.connectedDoor.destination, closestCity.flyDoor.position)] + cityPath.dijsktraPath # Just go up
            cityPath.dijsktraDistance += cityPath.dijsktraPath[0][-1].g # Normally just 1



###############################################################################################################
# Returns last door you need to go through, its distance from the player, and its distance to the destination #
###############################################################################################################
def getPlayerDistance(playerPath, destination, closestDoor, closestPositionDoor, pathToDoor):

    # We already ruled out direct path to destination, so we have to go through at least one door
    if (closestPositionDoor.connectedDoor == closestDoor):
        playerPath.lastDoorDestination = closestPositionDoor.destination
        playerPath.dijsktraPath = [pathToDoor]
        playerPath.dijsktraDistance = pathToDoor[-1].g
        playerPath.finalPath = getMostEfficientPath(playerPath.lastDoorDestination, destination)
        playerPath.finalDistance = playerPath.finalPath[-1].g

    # Need to go through at least one door
    else:
        # Calculate distance from current position's nearest door to location's nearest door
        paths, distancesFromPlayer = dijkstra(closestPositionDoor.createDoorKey())
        dijsktraPlayerPath = processDijkstraPath(paths, closestDoor.createDoorKey())

        lastSubpathDoor = closestPositionDoor

        # Check if any of the doors before closestDoor can reach the destination
        for doorId in range(0, len(dijsktraPlayerPath)):

            # Check if we can directly reach destination from there
            playerPath.finalPath = getMostEfficientPath(lastSubpathDoor.destination, destination)

            if (playerPath.finalPath):
                break

            # We couldn't find a path from last door, keep following the path
            lastSubpathDoor = getLastDoorInPath(dijsktraPlayerPath[doorId], dijsktraPlayerPath[doorId + 1])

        # Update dijsktraPath with the new last door destination
        dijsktraPlayerPath = dijsktraPlayerPath[:doorId + 1]
        playerPath.lastDoorDestination = lastSubpathDoor.destination
        playerPath.finalDistance = playerPath.finalPath[-1].g

        # Only one door : skip dijsktraPlayerPath
        if (len(dijsktraPlayerPath) == 1):
            playerPath.dijsktraDistance = pathToDoor[-1].g
            playerPath.dijsktraPath = [pathToDoor] + [playerPath.finalPath]

        # Need to go through at least two doors : keep dijsktraPlayerPath
        else:
            playerPath.dijsktraDistance = pathToDoor[-1].g + distancesFromPlayer[lastSubpathDoor.createDoorKey()]
            playerPath.dijsktraPath = [pathToDoor] + [dijsktraPlayerPath] + [playerPath.finalPath]


#############################################
# Find closest door to the desired location #
#############################################
def getClosestDoor(location: Position):

    # Get all doors in the zone and sort them by distance to the desired location
    closestDoors = sorted(location.zone.doorList, key = lambda door: door.position.getDistanceTo(location))
    currentClosestDoor = None
    doorCost = None

    # Retrieve the closest possible door that can actually lead to the location
    for door in closestDoors:

        # Get the path from the nearest door
        doorPath = getMostEfficientPath(door.connectedDoor.destination, location, maxCost = doorCost)

        # If a second path has been found with maxCost on, return it, if not the currentClosestDoor is the better option
        if (currentClosestDoor):
            return door if doorPath else currentClosestDoor

        # First path has been found, since we're most likely between two doors, we'll compare them
        if (doorPath):
            currentClosestDoor = door
            doorCost = doorPath[-1].g

    # Default : maybe there only was one available path, return currentClosestDoor
    return currentClosestDoor


#######################################################################
# Get the closest door to the player that can lead to the destination #
#######################################################################
def getBestPathDoor(playerPosition, destinationDoorKey):

    # Sort doors by distance to destination
    doorListByTrueDistance = []

    # Calculate distance from every door in the zone to destination
    for door in playerPosition.zone.doorList:
        distances = dijkstra(door.createDoorKey())[1]

        if (destinationDoorKey in distances):
             doorListByTrueDistance.append([distances[destinationDoorKey], door])

    # Sort doors by true distance to destination
    closestDoors = sorted(doorListByTrueDistance, key = lambda door: door[0])

    # Retrieve the closest possible door that the player can reach
    for door in closestDoors:

        # Get the path from current position to best door
        doorPath = getMostEfficientPath(playerPosition, door[1].position)

        # Path has been found to a near door, return it
        if (doorPath):
            return door[1], doorPath
        
    return None, None


###########################################################
# Get last position after going from startDoor to endDoor #
###########################################################
def getLastDoorInPath(startDoorKey, endDoorKey):

    # Retrieve every path from the starting door
    possiblePaths = DOOR_GRAPH[startDoorKey]

    # Find its connection to the last door to get the final door
    for doorNode in possiblePaths:
        if (doorNode.fromDoor in startDoorKey and doorNode.toDoor in endDoorKey):
            return doorNode.toDoor
        

#############################################################################################
# Find closest zone to current player position where you can Dig or Fly and return its path #
#############################################################################################
def findClosestFlyDigZone(playerPosition: Position):

    # Find closest door to the player
    closestNeighbourDoors = sorted(playerPosition.zone.doorList, key = lambda door: door.position.getDistanceTo(playerPosition))
    startingDoor = closestNeighbourDoors[0]

    # Get all possible paths from closest door sorted by distance
    paths, distances = dijkstra(startingDoor.createDoorKey())
    closestDoors = sorted(distances.items(), key = lambda distance: distance[1])

    # Find closest door that leads to a zone you can dig or fly
    for doorKey, distance in closestDoors:
        if (doorKey[0].destination.zone.canFly or doorKey[0].destination.zone.canDig):
            endDoor = doorKey[0]
            break

        if (doorKey[1].destination.zone.canFly or doorKey[1].destination.zone.canDig):
            endDoor = doorKey[1]
            break

    # Return complete path
    return endDoor.destination, generateWorldPath(endDoor, skipAllCityProcesses = True)[1]
